name: cypressoft_practical_task
description: Cypressoft Practical Task for job recruitment

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  http: ^0.13.5
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

#  fonts:
#    - family: Comfortaa
#      fonts:
#        - asset: fonts/Comfortaa-Regular.ttf
#        - asset: fonts/Comfortaa-Bold.ttf
#
#    - family: Inter
#      fonts:
#        - asset: fonts/Inter-Regular.ttf
#        - asset: fonts/Inter-Bold.ttf
